using System.Text;

namespace DocSamples;

/// <summary>
/// Owns the documentation-artifact page template and the shared stylesheet, per
/// <c>docs/design/doc-artifacts.md</c>: <c>HtmlSink</c> stays a fragment renderer; the page shell
/// (document skeleton, headings, captions, CSS) lives here. Output is deterministic — no dates,
/// no tool versions, LF line endings only.
/// </summary>
public static class DocPage
{
    /// <summary>One section of an example page: a heading, an explanation, an optional source
    /// listing (e.g. the markup that produced the fragment), and the rendered fragment.</summary>
    public sealed record Section(string Heading, string Description, string? Source, string FragmentHtml);

    /// <summary>
    /// The shared stylesheet written to <c>docs/examples/assets/tigercli.css</c>. Styles the page
    /// shell plus the stable <c>HtmlSink</c> classes documented in <c>docs/reference/html-sink.md</c>
    /// (<c>.tigercli</c>, <c>.tc-bold</c>, <c>.tc-italic</c>, <c>.tc-underline</c>, <c>.tc-link</c>).
    /// Colours in fragments are deterministic inline hex and need no stylesheet support.
    /// </summary>
    // Normalized to LF because raw string literals carry the source file's line endings, and the
    // repo's .gitattributes checks .cs files out as CRLF — artifacts must stay LF either way.
    public static readonly string Css = CssRaw.Replace("\r\n", "\n");

    private const string CssRaw = """
        /* TigerCli documentation artifacts — generated by internal/DocSamples.
           Do not edit by hand: edit DocPage.Css in internal/DocSamples and regenerate
           (dotnet run --project internal/DocSamples). */

        :root { color-scheme: dark; }

        body {
          margin: 0;
          background: #14161a;
          color: #d4d4d4;
          font-family: "Segoe UI", system-ui, Arial, sans-serif;
          line-height: 1.5;
        }

        main { max-width: 980px; margin: 0 auto; padding: 24px 20px 48px; }

        h1 { font-size: 22px; margin: 0 0 4px; }
        h2 { font-size: 16px; margin: 32px 0 6px; border-bottom: 1px solid #33363d; padding-bottom: 4px; }
        p { margin: 6px 0; color: #b9bec7; max-width: 78ch; }
        p.intro { color: #d4d4d4; }
        footer { margin-top: 40px; font-size: 12px; color: #7d828b; }

        /* Rendered terminal fragments (HtmlSink output). Grid renders carry the default
           silver-on-black ink inline, so the surface is near-black with a light foreground
           for unstyled (markup-only) runs. */
        pre.tigercli {
          background: #0c0c0c;
          color: #c0c0c0;
          padding: 12px 14px;
          border-radius: 6px;
          border: 1px solid #2a2d34;
          overflow-x: auto;
          font-family: "Cascadia Mono", Consolas, "DejaVu Sans Mono", monospace;
          font-size: 14px;
          line-height: 1.3;
        }

        /* Source listings (the markup/code that produced a fragment). */
        pre.tc-source {
          background: #1b1e24;
          color: #9da5b0;
          padding: 8px 14px;
          border-radius: 6px;
          overflow-x: auto;
          font-family: "Cascadia Mono", Consolas, "DejaVu Sans Mono", monospace;
          font-size: 13px;
        }

        /* Stable HtmlSink decoration/link-role classes. */
        .tc-bold { font-weight: 700; }
        .tc-italic { font-style: italic; }
        .tc-underline { text-decoration: underline; }
        .tc-link { text-decoration: underline; }
        pre.tigercli a { color: inherit; }
        """;

    /// <summary>Builds a full example page. All shell text is HTML-escaped; fragment HTML is
    /// inserted verbatim (it is already escaped by <c>HtmlSink</c>).</summary>
    public static string BuildPage(string title, string intro, IReadOnlyList<Section> sections)
    {
        var sb = new StringBuilder();
        sb.Append("<!DOCTYPE html>\n");
        sb.Append("<html lang=\"en\">\n<head>\n");
        sb.Append("<meta charset=\"utf-8\">\n");
        sb.Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
        sb.Append("<title>").Append(Escape(title)).Append(" — TigerCli examples</title>\n");
        sb.Append("<link rel=\"stylesheet\" href=\"assets/tigercli.css\">\n");
        sb.Append("</head>\n<body>\n<main>\n");
        sb.Append("<h1>").Append(Escape(title)).Append("</h1>\n");
        sb.Append("<p class=\"intro\">").Append(Escape(intro)).Append("</p>\n");

        foreach (var section in sections)
        {
            sb.Append("<section>\n");
            sb.Append("<h2>").Append(Escape(section.Heading)).Append("</h2>\n");
            sb.Append("<p>").Append(Escape(section.Description)).Append("</p>\n");
            if (section.Source is not null)
                sb.Append("<pre class=\"tc-source\">").Append(Escape(section.Source)).Append("</pre>\n");
            sb.Append(section.FragmentHtml).Append('\n');
            sb.Append("</section>\n");
        }

        sb.Append("<footer>Generated by internal/DocSamples from real TigerCli rendering. ");
        sb.Append("Do not edit by hand — regenerate with: dotnet run --project internal/DocSamples</footer>\n");
        sb.Append("</main>\n</body>\n</html>\n");
        return sb.ToString();
    }

    private static string Escape(string text) => text
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;");
}
